[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tapo-camera-mcp"
version = "0.2.0"
description = "FastMCP 2.10 server for controlling TP-Link Tapo cameras"
requires-python = ">=3.8"
dependencies = [
    "fastmcp>=2.10.0",
    "pytapo>=3.3.48",
    "pydantic>=2.0.0",
    "python-dotenv>=1.0.0",
    "aiohttp>=3.9.0",
]
